### ISSUE TITLE
Add support for Guzzle5

### ISSUE THREAD

**Issue by cpliakas** [acquia/http-hmac-php#1]
We need a [RequestInterface](https://github.com/acquia/http-hmac-php/blob/master/src/Request/RequestInterface.php) implementation for Guzzle5 as well as an Auth Plugin modeled after the one implemented for [Guzzle3](https://github.com/acquia/http-hmac-php/tree/master/src/Guzzle3).

**Comment by cpliakas** [comment]
Fixed by #5.

**Comment by cpliakas** [comment]
Great work @charuag!

**Comment by danmatthews** [comment]
Any usage examples anywhere for using this with Guzzle 5?

Thanks.
