### ISSUE TITLE
Implement v2 of the HTTP HMAC Spec

### ISSUE THREAD

**Issue by cpliakas** [acquia/http-hmac-php#13]
Version 1 is effectively deprecated, v2 is the latest and greatest. We should implement v2 of the spec in this library.

This will likely be a massive refactoring, so this will result in a 3.0 version of this library. We can therefore drop support for the V1 version of the algorithm, as if you are using V1 then you should stick with the V2 version of this library.

**Comment by kevinhankens** [comment]
https://github.com/acquia/http-hmac-php/pull/14/files

**Comment by itafroma** [comment]
3.0.0 final, with v2 support, has been tagged today.

**Comment by cpliakas** [comment]
BOOM! Well done, team!!
