### ISSUE TITLE
RequestAuthenticator.php and ResponseAuthenticator.php are vulnerable to timing attacks

### ISSUE THREAD

**Issue by natnet00** [acquia/http-hmac-php#20]
In both files equals operators are used to test the expected hmac against the calculated hmac.
This makes the check susceptible to timing attacks.

Instead you should use: hash_equals(hmac1, hmac2) - available since PHP 5.6

**Comment by itafroma** [comment]
Thanks for the report! I've opened a PR to fix this issue: #21
