### ISSUE TITLE
Response::getBody->getContents() returns empty string

### ISSUE THREAD

**Issue by mhouriet** [acquia/http-hmac-php#34]
Hey,

In `ResponseSigner.php` the `Response` body stream in being consumed by `signResponse()` at line 60. Although explicit casting using `__toString()` will always rewind a stream before reading it, calling the `getContents()` method from `StreamInterface` will not. As a result, the middleware is breaking expected behavior, since `Response::getBody()->getContents()` will always return empty string after a POST.

I fixed it with a simple `$response->getBody()->rewind()` just after assigning $parts. I guess you can also use `tell()` and the `seek()` but I failed to find any real-life scenarios where it would make sense for a middleware to start reading the stream halfway through.

Do you want a pull request for this or is the fix trivial enough like this?

Cheers,

Matt

**Comment by itafroma** [comment]
Thanks for the report! Pull requests are always welcome. It would be good to get a unit test for ResponseSigner to ensure this fix isn't inadvertently reverted in the future.

**Comment by mhouriet** [comment]
Oh, of course :) There you go, https://github.com/acquia/http-hmac-php/pull/35
