### ISSUE TITLE
Symfony2

### ISSUE THREAD

**Issue by Gladhon** [acquia/http-hmac-php#7]
I've written a Symfony2 Integration, can you take a look and tell me your opinion 
https://github.com/ibrows/IbrowsHmacBundle

**Comment by cpliakas** [comment]
@Gladhon This looks great! Thanks for sharing. I've done some security stuff for Silex which I believe uses the same Symfony component, and there is a lot of similarities between our code. I am glad you released something open source and generic that others can benefit from. Great work.
